clc;clear;
A = [1 2 0 1;0 1 1 0;1 2 0 1];
disp("The given matrix is:");
disp(A);
[m,n] = size(A);
disp(m,"m = ");
disp(n,"n = ");
[v,pivot] = rref(A);
disp(rref(A),"Row Reduced Echelon Form: ");
r = length(pivot);
disp(r,"Rank: ");
colspace = A(:,pivot);
disp(colspace,"Column Space: ");
nullspace = kernel(A);
disp(nullspace,"Null Space: ");
rowspace = v(1:r,:)';
disp(rowspace,"Row Space: ");
leftnullspace = kernel(A');
disp(leftnullspace,"Left Null Space: ");
